name: Deploy to GitHub Pages

on:
  # Se activa cuando se hace un push a la rama main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verificar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js (si usas JavaScript)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar dependencias (si tienes un package.json)
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el proyecto (si tienes scripts de construcción)
      - name: Build project
        run: npm run build

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
