name: Deploy CryptoEduar to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias (si las hay)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Construir el sitio (opcional, solo si usas frameworks como React/Vite)
        run: echo "No build necesario para HTML/CSS/JS plano"

      - name: Subir archivos a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # sube toda la carpeta actual, asegúrate de que index.html esté en raíz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
